# Lecture 17-Orthogonal basis and Orthogonal Matrix

## Orthonormal vectors

$$
q_i^T q_j =
\begin {cases}
0 &\text {\(i \neq j \)}  \\
1 &\text {\(i=j \)}  \\
\end {cases}
$$

## Orthogonal matrix

$$ 
Q = [q_1, q_2, \cdots, q_n] \\ 
$$ 
$Q$ is orthonormal if $ Q^T Q = I $

That means $Q$ is a square matrix and its columns are orthonormal vectors.

If $Q^T Q = I$, that means $ Q^{-1} = Q^T$

Here are some examples of orthonormal matrix:

Example 1:
$$
\begin {bmatrix}
\frac {1}{\sqrt{2}} & \frac {1}{\sqrt{2}} \\
\frac {1}{\sqrt{2}} & -\frac {1}{\sqrt{2}} \\
\end {bmatrix}
$$

Example 2: rotation matrix
$$
\begin {bmatrix}
\cos\theta & -\sin\theta \\
\sin\theta & \cos\theta \\
\end {bmatrix}
$$

Example 3: Hadamard matrix
$$
\frac {1}{2}
\begin {bmatrix}
1 & 1 & 1 & 1 \\
1 & -1 & 1 & -1 \\ 
1 & 1 & -1 & -1 \\
1 & -1 & -1 & 1 \\ 
\end {bmatrix}
$$

$Q$ is a square matrix that has orthonormal columns, projection matrix onto the column space will be:
$$
P = Q(Q^T Q)^{-1} Q^T = Q Q^T = I
$$

There is:
$$
A^T A \hat{x}= b 
$$

But now $A$ is $Q$ and $Q$ is orthonormal matrix, so:
$$
Q^T Q \hat{x} = Q^T b \\
\hat{x} = Q^T b \\
\hat{x_i} = q_i^T b
$$





## The Gram-Schmidt process

Our goal is to find an orthonormal basis for the column space of $A$.

We have independent vectors $a, b, c$, we want to find $q_1, q_2, q_3$ that are orthonormal vectors and span the same space as $a, b, c$. Vectors $p, q$ are the projections of $c$ onto the vectors $a, b$. Vector $r$ is the projection of $b$ onto $a$.

$$
A = a \\
B = b - r = b - \frac {A^T b}{A^T A} A \\
C = c - p - q = c - \frac {A^T c}{A^T A} A- \frac {B^T c}{B^T B} B \\
q_1 = \frac {a}{\|a\|} \\
q_2 = \frac {B}{\|B\|} \\
q_3 = \frac {C}{\|C\|} \\
$$

## The gram_schmidt function

In [13]:
import numpy as np
import numpy.linalg as la

def orthogonalize(U, eps=1e-15):
    """
    Orthogonalizes the matrix U (d x n) using Gram-Schmidt Orthogonalization.
    If the columns of U are linearly dependent with rank(U) = r, the last n-r columns 
    will be 0.
    
    Args:
        U (numpy.array): A d x n matrix with columns that need to be orthogonalized.
        eps (float): Threshold value below which numbers are regarded as 0 (default=1e-15).
    
    Returns:
        (numpy.array): A d x n orthogonal matrix. If the input matrix U's cols were
            not linearly independent, then the last n-r cols are zeros.
    
    Examples:
    ```python
    >>> import numpy as np
    >>> import gram_schmidt as gs
    >>> gs.orthogonalize(np.array([[10., 3.], [7., 8.]]))
    array([[ 0.81923192, -0.57346234],
       [ 0.57346234,  0.81923192]])
    >>> gs.orthogonalize(np.array([[10., 3., 4., 8.], [7., 8., 6., 1.]]))
    array([[ 0.81923192 -0.57346234  0.          0.        ]
       [ 0.57346234  0.81923192  0.          0.        ]])
    ```
    """
    
    n = len(U[0])
    # numpy can readily reference rows using indices, but referencing full rows is a little
    # dirty. So, work with transpose(U)
    V = U.T
    for i in range(n):
        prev_basis = V[0:i]     # orthonormal basis before V[i]
        coeff_vec = np.dot(prev_basis, V[i].T)  # each entry is np.dot(V[j], V[i]) for all j < i
        # subtract projections of V[i] onto already determined basis V[0:i]
        V[i] -= np.dot(coeff_vec, prev_basis).T
        if la.norm(V[i]) < eps:
            V[i][V[i] < eps] = 0.   # set the small entries to 0
        else:
            V[i] /= la.norm(V[i])
    return V.T

In [14]:
orthogonalize(np.array([[10., 3.], [7., 8.]]))

array([[ 0.81923192, -0.57346234],
       [ 0.57346234,  0.81923192]])

In [15]:
orthogonalize(np.array([[1., 1.], [1., 0],[1, 2]]))

array([[ 5.77350269e-01, -1.57009246e-16],
       [ 5.77350269e-01, -7.07106781e-01],
       [ 5.77350269e-01,  7.07106781e-01]])

## The gram_schmidt function in Sympy

In [16]:
from sympy import Matrix
from sympy.matrices.dense import GramSchmidt as gs
vlist = [Matrix([3, 0]), Matrix([2, 2])]
gs(vlist, True)

[Matrix([
 [1],
 [0]]),
 Matrix([
 [0],
 [1]])]

In [17]:
M = Matrix([[1., 1.], [1., 0],[1, 2]])
M.QRdecomposition()

(Matrix([
 [0.577350269189626,                  0],
 [0.577350269189626, -0.707106781186547],
 [0.577350269189626,  0.707106781186547]]),
 Matrix([
 [1.73205080756888, 1.73205080756888],
 [               0,  1.4142135623731]]))

In [25]:
from sympy import symbols

a, b, c, d = symbols('a b c d')
M = Matrix([[a, 1], [b, 2]])
M.QRdecomposition()[0]

Matrix([
[a/sqrt(Abs(a)**2 + Abs(b)**2), (-a*conjugate(a)/(a*conjugate(a) + b*conjugate(b)) - 2*a*conjugate(b)/(a*conjugate(a) + b*conjugate(b)) + 1)/sqrt(Abs(a*conjugate(a)/(a*conjugate(a) + b*conjugate(b)) + 2*a*conjugate(b)/(a*conjugate(a) + b*conjugate(b)) - 1)**2 + Abs(b*conjugate(a)/(a*conjugate(a) + b*conjugate(b)) + 2*b*conjugate(b)/(a*conjugate(a) + b*conjugate(b)) - 2)**2)],
[b/sqrt(Abs(a)**2 + Abs(b)**2), (-b*conjugate(a)/(a*conjugate(a) + b*conjugate(b)) - 2*b*conjugate(b)/(a*conjugate(a) + b*conjugate(b)) + 2)/sqrt(Abs(a*conjugate(a)/(a*conjugate(a) + b*conjugate(b)) + 2*a*conjugate(b)/(a*conjugate(a) + b*conjugate(b)) - 1)**2 + Abs(b*conjugate(a)/(a*conjugate(a) + b*conjugate(b)) + 2*b*conjugate(b)/(a*conjugate(a) + b*conjugate(b)) - 2)**2)]])

In [26]:
M.QRdecomposition()[1]

Matrix([
[sqrt(Abs(a)**2 + Abs(b)**2),                                                                                                             (conjugate(a)/(a*conjugate(a) + b*conjugate(b)) + 2*conjugate(b)/(a*conjugate(a) + b*conjugate(b)))*sqrt(Abs(a)**2 + Abs(b)**2)],
[                          0, sqrt(Abs(a*conjugate(a)/(a*conjugate(a) + b*conjugate(b)) + 2*a*conjugate(b)/(a*conjugate(a) + b*conjugate(b)) - 1)**2 + Abs(b*conjugate(a)/(a*conjugate(a) + b*conjugate(b)) + 2*b*conjugate(b)/(a*conjugate(a) + b*conjugate(b)) - 2)**2)]])

## A = QR

$Q$ is the orthonormal matrix, $R$ is upper triangular matrix.

In [19]:
import numpy as np
import numpy.linalg as la

la.qr(np.array([[10., 3.], [7., 8.]]))

(array([[-0.81923192, -0.57346234],
        [-0.57346234,  0.81923192]]),
 array([[-12.20655562,  -7.04539452],
        [  0.        ,   4.83346833]]))

In [20]:
la.qr(np.array([[1., 1.], [1., 0],[1, 2]]))

(array([[-5.77350269e-01, -9.33980149e-17],
        [-5.77350269e-01, -7.07106781e-01],
        [-5.77350269e-01,  7.07106781e-01]]),
 array([[-1.73205081, -1.73205081],
        [ 0.        ,  1.41421356]]))