# Lecture 15: Projections

## Plotting a projection

In [1]:
import plotly.figure_factory as ff
import numpy as np
import plotly.graph_objects as go

a = np.array([4,4])
b = np.array([1,5])

# p is the projection of b onto a
p = np.dot(b,a)/np.dot(a,a) * a
e = b-p

x,y = np.array([0,0,p[0]]), np.array([0,0,p[1]])
u,v = np.array([a[0],b[0],e[0]]), np.array([a[1],b[1],e[0]])

fig = ff.create_quiver([0], [0], [a[0]], [a[1]],
                        scale=1,
                        arrow_scale=.06,
                        name='Vector a',
                        line_width=1,
                        scaleratio=1, 
                        )

fig2 = ff.create_quiver([0], [0], [b[0]], [b[1]],
                        scale=1,
                        arrow_scale=.06,
                        name='Vector b',
                        line_width=1,
                        scaleratio=1, 
                        )

fig3 = ff.create_quiver([0], [0], [p[0]], [p[1]],
                        scale=1,
                        arrow_scale=.06,
                        name='Vector p',
                        line_width=1,
                        scaleratio=1, 
                        )

fig4 = ff.create_quiver([p[0]], [p[1]], [e[0]], [e[1]],
                        scale=1,
                        arrow_scale=.06,
                        name='Vector e',
                        line_width=1,
                        scaleratio=1, 
                        )

fig.add_traces(data = fig2.data)
fig.add_traces(data = fig3.data)
fig.add_traces(data = fig4.data)

fig.add_trace(go.Scatter(x=[a[0]], 
                    y=[a[1]],
                    mode='markers+text',
                    text=['a'],
                    marker_size=12,
                    textposition="top center",
                    name='a'))

fig.add_trace(go.Scatter(x=[b[0]], 
                    y=[b[1]],
                    mode='markers+text',
                    text=['b'],
                    marker_size=12,
                    textposition="top center",
                    name='b'))

fig.add_trace(go.Scatter(x=[p[0]], 
                    y=[p[1]],
                    mode='markers+text',
                    text=['p'+np.array2string(p)],
                    marker_size=12,
                    textposition="middle right",
                    name='p'))

fig.show()

## Projection formula proof

Proof:

let $ p = x * a$  and  $ e = b - p $

e is orthogonal to a

$ e \cdot a = 0 $

$ (b - p) \cdot a = 0 $

$ (b - x * a) \cdot a = 0 $

$ b \cdot a - x * a \cdot a = 0 $

$ x * a \cdot a = b \cdot a $

$ x = \frac{b \cdot a}{a \cdot a} $

$ p = \frac{b \cdot a}{a \cdot a} * a $

## Projection Matrix

What is the Projection Matrix?

$ P = \frac{a * a^T}{a^T * a} $

The properties of the projection matrix P:

- $ P^2 = P $
- $ P^T = P $
- $ rank(P) = 1 $

In [2]:
import sympy

a = sympy.Matrix([4,4])
a

Matrix([
[4],
[4]])

In [3]:
a.T

Matrix([[4, 4]])

In [4]:
a * a.T

Matrix([
[16, 16],
[16, 16]])

In [5]:
a.dot(a)

32

In [6]:
P = a * a.T / a.dot(a)
P

Matrix([
[1/2, 1/2],
[1/2, 1/2]])

In [7]:
P * P

Matrix([
[1/2, 1/2],
[1/2, 1/2]])

In [8]:
P.rank()

1

In [9]:
P.T == P

True

## Why project?

Because $ Ax = b $ may not have a solution, solve $ Ax = p $ instead. This is the closest we can get to a solution.

## Projection onto a plane or n-dimensional subspace

There is a plane, the basis vectors are $ a_1 $ and $ a_2 $, and we want to project $ b $ onto the plane, and get the projection vector $ p $, the error $ e = b - p $.

$$
p = x_1 * a_1 + x_2 * a_2 = A * \hat{x} \\
$$

The key is $ b - A * \hat{x} $ is orthogonal to the plane.

So we get
$$
a_1^T * (b - A * \hat{x}) = 0 \\
a_2^T * (b - A * \hat{x}) = 0
$$

Rewrite the equations above in matrices form:
$$
A^T * (b - A * \hat{x}) = 0 \\
$$

$ e $ is in the nullspace of $ A^T $. $ e $ is orthogonal to the column space of $ A $. Solve this equation, we can get $ \hat{x} $.

$$
A^T * A * \hat{x} = A^T * b \\
\hat{x} = (A^T * A)^{-1} * A^T * b \\
p = A * \hat{x} = A * (A^T * A)^{-1} * A^T * b \\
P = A * (A^T * A)^{-1} * A^T \\
$$



$ A $ is not a square matrix, so $ A^-1 $ does not exist. But $ A^T * A $ is a square matrix, so $ (A^T * A)^{-1} $ exists. 

## Projection onto a plane equation with Sympy

In [2]:
from sympy import *
init_printing(use_unicode=True)

In [3]:
a1, a2, b, A, p, e, x1, x2, x_hat, P = symbols("a1 a2 b A p e x1 x2 x_hat P")

a1 = Matrix([1, 0, 0])
a2 = Matrix([1, 2, 2])
b = Matrix([1, -2, 1])

In [4]:
A = a1.col_insert(1, a2)
A

⎡1  1⎤
⎢    ⎥
⎢0  2⎥
⎢    ⎥
⎣0  2⎦

In [5]:
p = x1 * a1 + x2 * a2
p

⎡x₁ + x₂⎤
⎢       ⎥
⎢ 2⋅x₂  ⎥
⎢       ⎥
⎣ 2⋅x₂  ⎦

In [6]:
x_hat = Matrix([x1, x2])
x_hat

⎡x₁⎤
⎢  ⎥
⎣x₂⎦

In [7]:
A * x_hat

⎡x₁ + x₂⎤
⎢       ⎥
⎢ 2⋅x₂  ⎥
⎢       ⎥
⎣ 2⋅x₂  ⎦

In [8]:
e = b-p
e

⎡-x₁ - x₂ + 1⎤
⎢            ⎥
⎢ -2⋅x₂ - 2  ⎥
⎢            ⎥
⎣  1 - 2⋅x₂  ⎦

In [9]:
Eq(e.dot(a1), 0) 

In [10]:
Eq(e.dot(a2),0)

In [11]:
[e.dot(a1), e.dot(a2)]

In [12]:
answer = linsolve([e.dot(a1), e.dot(a2)], (x1, x2))
x1 = answer.args[0][0]
x2 = answer.args[0][1]

In [13]:
x1, x2

In [14]:
p = x1 * a1 + x2 * a2
p

⎡ 1  ⎤
⎢    ⎥
⎢-1/2⎥
⎢    ⎥
⎣-1/2⎦

In [15]:
e = b - p
e

⎡ 0  ⎤
⎢    ⎥
⎢-3/2⎥
⎢    ⎥
⎣3/2 ⎦

In [16]:
e.dot(p)

In [17]:
e.dot(a1)

In [18]:
e.dot(a2)

In [19]:
(A.T * A).inv()

⎡9/8   -1/8⎤
⎢          ⎥
⎣-1/8  1/8 ⎦

In [20]:
P = A * (A.T * A).inv() * A.T
P

⎡1   0    0 ⎤
⎢           ⎥
⎢0  1/2  1/2⎥
⎢           ⎥
⎣0  1/2  1/2⎦

In [21]:
P * P

⎡1   0    0 ⎤
⎢           ⎥
⎢0  1/2  1/2⎥
⎢           ⎥
⎣0  1/2  1/2⎦

In [22]:
P * b

⎡ 1  ⎤
⎢    ⎥
⎢-1/2⎥
⎢    ⎥
⎣-1/2⎦

In [23]:
p == P * b

True

## Plotting with Plotly

In [24]:
import plotly.graph_objects as go
import plotly.figure_factory as ff
import numpy as np

a1 = np.array([[1, 0, 0]]).T
a2 = np.array([[1, 2, 2]]).T
b = np.array([[1, -2, 1]]).T
a1, a2, b

(array([[1],
        [0],
        [0]]),
 array([[1],
        [2],
        [2]]),
 array([[ 1],
        [-2],
        [ 1]]))

In [25]:
A = np.concatenate((a1, a2), axis=1)
A, A.T

(array([[1, 1],
        [0, 2],
        [0, 2]]),
 array([[1, 0, 0],
        [1, 2, 2]]))

In [26]:
x1, x2 = 5/4, -1/4
x_hat = np.array([[x1, x2]]).T
x_hat

array([[ 1.25],
       [-0.25]])

In [27]:
p = A @ x_hat
p

array([[ 1. ],
       [-0.5],
       [-0.5]])

In [28]:
e = b - p
e

array([[ 0. ],
       [-1.5],
       [ 1.5]])

In [29]:
np.dot(e.T[0], p.T[0])

In [30]:
np.dot(e.T[0], a1.T[0])

In [31]:
np.dot(e.T[0], a2.T[0])

In [35]:
from numpy.linalg import inv
inv(A.T @ A)

array([[ 1.125, -0.125],
       [-0.125,  0.125]])

In [38]:
from numpy.linalg import inv
P = A @ inv(A.T @ A) @ A.T
P

array([[1. , 0. , 0. ],
       [0. , 0.5, 0.5],
       [0. , 0.5, 0.5]])

In [39]:
P @ P

array([[1. , 0. , 0. ],
       [0. , 0.5, 0.5],
       [0. , 0.5, 0.5]])

In [40]:
P @ b

array([[ 1. ],
       [-0.5],
       [-0.5]])

In [43]:
import plotly.graph_objects as go
import plotly.figure_factory as ff
import numpy as np



x, y = np.linspace(-5, 5, 100), np.linspace(-5, 5, 100)
z = np.tile(y,(100,1))

fig = go.Figure(data=[go.Surface(z=z, x=x, y=y,surfacecolor=x)])

fig.update_layout(title='Flat Surface', autosize=False,
                    width=500, height=500,
                    margin=dict(l=65, r=50, b=65, t=90))



fig.show()

## Least Squares